name: Nueva funci贸n
description: Solicitar una nueva funci贸n
labels: ["new-function"]
body:
  - type: textarea
    id: detalle
    attributes: { label: Descripci贸n de la nueva funci贸n }
    validations: { required: true }
